name: Run tests using Vitest

on:
    push:
        branches:
            - '**'
        paths-ignore:
            - 'README.md'
            - 'CHANGELOG.md'
            - 'LICENSE'
            - '.github/**'
            - '.gitignore'
            - '.prettierrc'
            - '.prettierignore'
    pull_request:
        branches:
            - master
        paths-ignore:
            - 'README.md'
            - 'CHANGELOG.md'
            - 'LICENSE'
            - '.github/**'
            - '.gitignore'
            - '.prettierrc'
            - '.prettierignore'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: latest
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            - run: pnpm install --frozen-lockfile
            - run: pnpm run lint
            - run: pnpm run test
